[package]
name = "rusticade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
cmp = "0.0.0"
log = "0.4.20"
rand = "0.8.5"
ruscii = "0.4.0"
